### ISSUE TITLE
Does it work with firebase messaging?

### ISSUE THREAD

**Issue by crushman1** [BaseflowIT/flutter-geolocator#214]
## 🐛 Bug Report

For some reason my flutter project does not build once firestore_messaging and geolocator are in the dependencies together. I get the error :
D8: Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

full error : 

```
Note: C:\Users\rg\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\firebase_messaging-2.2.0+1\android\src\main\java\io\flutter\plugins\firebasemessaging\FlutterFirebaseInstanceIDService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
D8: Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver
         *********************************************************
WARNING: This version of cloud_firestore will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\2.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\3.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\4.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\5.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\6.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\7.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\8.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\9.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\10.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\11.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\12.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\13.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\14.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\15.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\16.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\17.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\18.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\19.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\20.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\21.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\22.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\23.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\24.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\25.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\26.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\27.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\28.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\29.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\30.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\31.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\32.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\33.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\34.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\35.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\36.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\37.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\38.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\39.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\40.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\41.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\42.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\43.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\44.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\45.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\46.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\47.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\48.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\49.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\50.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\51.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\52.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\53.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\54.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\55.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\56.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\57.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\58.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\59.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\60.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\61.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\62.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\63.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\64.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\65.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\66.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\67.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\68.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\69.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\70.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\71.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\72.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\73.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\74.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\75.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\76.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\77.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\78.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\79.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\80.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\81.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\82.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\83.jar, C:\apps\tyronewrecking\build\app\intermediates\transforms\dexBuilder\debug\84.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 4s
Finished with error: Gradle task assembleDebug failed with exit code 1`

```
### Expected behavior
I expect it to build 
### Reproduction steps
Just add firestore_messaging to your dependencies. any version.

### Configuration
gradle 3.2.1
already did the : multiDexEnabled true

```
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^3.0.3
  location: ^1.4.1
  geocoder: ^0.1.2
  cupertino_icons: ^0.1.2
  fluttertoast: ^2.0.9
  shared_preferences: ^0.4.3
  path_provider: ^0.5.0+1
  firebase_messaging: ^2.0.1
  cloud_firestore: ^0.9.0+2
  geolocator: ^3.0.0
```
**Version:** 1.x
all versions i can think of
**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment]
@crushman1 could you try with version 3.0.1 we just released? We have removed Kotlin dependencies and moved to gradle version 3.3.1 (firebase_messaging uses gradle 3.3.0).

**Comment by asapJ** [comment]
> @crushman1 could you try with version 3.0.1 we just released? We have removed Kotlin dependencies and moved to gradle version 3.3.1 (firebase_messaging uses gradle 3.3.0).

Wouldn't that force him to migrate his project to androidX?

**Comment by crushman1** [comment]
will check it for sure this weekend, have been crazy busy.

**Comment by mvanbeusekom** [comment]
Should have been solved in version 3.0.1 and higher

**Comment by wil93** [comment]
I am still having issues when firebase_messaging is in the dependencies with geolocator.

If I create a blank project, and add:

    firebase_messaging: ^5.1.2
    geolocator: ^5.1.0

(and configure firebase stuff in the build.gradle files and manifest and so on)

Then I get this error:

```
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.localbroadcastmanager:localbroadcastmanager' has different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath. You should manually set the same version via DependencyResolution
```

Note that, if I use the newest version of geolocator (5.1.1) I get an "earlier" error:

```
Because every version of flutter_test from sdk depends on meta 1.1.6 and geolocator >=5.1.1 depends on meta ^1.1.7, flutter_test from sdk is incompatible with geolocator >=5.1.1.
```

Any ideas on how to solve this?

**Comment by jonsamwell** [comment]
Same issue here

**Comment by AbhishekVel** [comment]
same issue here

**Comment by ckodai** [comment]
@wil93 I solved using this 

**android/build.gradle**

`    subprojects {
        project.configurations.all {
            resolutionStrategy.eachDependency { details ->

                if(details.requested.group == 'androidx.localbroadcastmanager'
                        && !details.requested.name.contains('androidx')){
                    details.useVersion "1.0.0"
                }
            }
        }
    }`
